sudo: required
dist: trusty
language: node_js
node_js:
- 6.2.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
before_install:
- openssl aes-256-cbc -K $encrypted_92b08e8fae7c_key -iv $encrypted_92b08e8fae7c_iv -in .travis/deployment_key.pem.enc -out .travis/deployment_key.pem -d
- npm install -g pr-bumper
- pr-bumper check
- cp .env.example .env
- sudo apt-get update
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- travis_retry npm install
script:
- npm test
- npm run build
after_success:
- npm run coveralls
before_deploy:
- eval "$(ssh-agent -s)" #start the ssh agent
- chmod 600 .travis/deployment_key.pem
- ssh-add .travis/deployment_key.pem
- pr-bumper bump
- git fetch --tags # make sure travis ci has all remote tags for changelog
- npm run preparepublish
env:
  global:
  # pr-bumper-GITHUB_TOKEN-ubiquits/ubiquits
  - secure: WeZNXT3vUR5B0eoYKnaMVV0ORHATzNkAV9+ZESCOumXHZlbBH/9lLNsTSFh2wPxWwZZXtYRo5knEV6o9sj1vQqWLua2EJN6Fxt6axEjm2Q0zhhhRsyH2OlBKF86cvdwUq97xmVJ1x2jUZkfSTXNjf9CIBmnjTLF/+PoytLAanD4Sz4loKaUKHzxpZHhQ28RmwdivmOx1sIMDWdfHw1UvFduSrSPELqg7ZaB8a0CX+jJ8WNjm4i1uqEWCS2G/0ezPVrYsFbxZ7eTl3zQ+ebIMP7vnE1qGzmS5ArFF9LaRMpIQgkMjY1IrMsuK1P/vYM68glqUnvn76FmobEMJ6ivXWDLiveekM8IkFCMs7vhnWv70k0bqlZG/1L1VJdj/a4dKqPhEsjv/78TzLLzvTj5h3da4Oo4dUlCdOtGRGR+GGKXUXTJS6n63h2d/C+cU31cDQC4yBaOF6dvJ/ICu/DnpHDGROjXhEBzfRBrqM+zCrJc4naJrAFIr7RsTBtnu6TJVoZY3h8y1HWIRT3fusP8Hzfb7wH2VbUZfN3Rxb2uK8R8ZCF4i7RxF+FTqBQAvbY909uLKg5Uf7EXhQxnlzJ/QTeH5wyJEVeh7ObpIsr9rRhzzYh1pZyHBhCUHb5R+aP2XqqsiCuM1JyB2zkfE2ws6OrlWjwm1O8YPSyS/Q/9pxcI=
  # RO_GH_TOKEN
  - secure: Fweuy/B9OzsZojhhEZXpeVdhszpymSm3zJ+8ki80ym4UevU4jq2E+XiNSlj8eQZ+4NjUGQSA6IqbtHDq5x1cEknB1nWKhX5khXiG3IsfCCWOBBf9/2n30u1/wwXx3MjihHXSER0e1dAS+neAcTipSrMjdGalOwX4DbUxG0ZAZFD6DEjiSS2nV5W97sRW3MG2Q5mz4OcsI7DM9FbICp3DlF+0BQbWs8A3H5r1lmmLSK/bz+ZgVwm8yCc0lL7ToqYavLUp4Kg0jNI7w9yz/Fv91N+hRNMJEaAAtOP4AFzWliAs+MmQ3d/Pv8E6mnfUmrUYkrXMJauohpSlpsK4GyMZt7ZDGhY59y/cd2JM+bEVCbKiElqr6aC7UwEiH62+T8MCkftjsspqUV+1wmdP9sNKlGWngCNVgrtn8bXpYwOGLmPqPp0RvlIzUF4dBYj0LybjSQPi+lACehoBZ3M4EGfuItXlAtSUKqQHSRXpVccjujuZ+4tz5I10Heo87cZHPNN/UP5kVWSITb45KJAApl7gsNUHCIIc5JGCId3S3QDeM18ow4/8mIG+8Mbjf6OshDm/R9VCqbAaIjCg6mDzat/V+pu52tjqNbMHwbveHnW/LduSBWSQzFG+8xJgMkjzyTyuxwoe7fFbrNtpZ7wPYzAEW/X781n3zF5XcqXNnwLvjHw=
deploy:
  provider: npm
  email: zak@ubiquits.com
  skip_cleanup: true
  api_key:
    secure: NTQtLuxaOqwgfTRBdki8KrQOWfTgoWt2VV+wxyykfk3TD6SCVVnEpBhcwqoIQR8CHyRANC9G1pxV1tRvZKfew5aPXatXkamWFSwnbFf878wi9kndqIKIYTKY+QwqFHTAoPg6T354jv0sOOd4018DCnA7gfoOr45P8VDrSN/77Vm6OasI7bMIoJGToHbt+MD+QGD1Q7EDDR6bHYkemY9XvUwyGYSaYXLmybpTwzWe1oW1xJ7PjQuE4KspGqN64rIK6QPj0H7pmx9F2mrUlNwakfQaVThSF2c8toSNsRcXtGW4AsE0eiKRcyQprEwojggUoJFPSR/iOLlFrWx4h2UvYjK2vyjDWXOnVRkMbKAj+ifXhpmiKm8tfWGKb2fGLKDAwthD2xVjkWMAQYb4I26fKQVp58q5gOS/AzBUERpBFzRzL7GhSZ1N6fxkjskKI6FNJs4J8+Zm6kqeCsSwYMD1NKYGk23FTbnUM80Cbg3VLCfr/2nXm6WT5ZYfNhC1HaGBRDrYIuHTWF0iXx0POsdBm43ZJQEE4xoP2zMMdiSh+FxFf3CNs4lGf2fm9g8mXO3oMTI5E7d07wJKCI3Ssqcp2DgfyUa6iF3ygwBgBFaT0OneUg1tFKsMjisU+g7uXq0mZTyBWTO0BMfz5nTPrtztFii2W/uxfSOdrIm/mJi6AqQ=
  on:
    branch: master
    tags: false
